### ISSUE TITLE
Persistent notification

### ISSUE THREAD

**Issue by xavihernandez** [brarcher/protect-baby-monitor#18]
Hi,

Not an issue but a suggestion, it could be good to have a persistent notification when app is running. It could show information about connection. 

I already have to put my ear close to speaker to be sure it still running. With a persistent notification this could be solved. 

Notification could be used to see if client is still connected to server with a state like : ON / OFF / ERROR (with a label like : server protocole error, connection lost, etc.). 
It could also switch on/off streaming (disconnect, connect to last server).
It can show other info about connection like address, poet, alias. 
Anyways these are just some ideas. Don't know if you are listening to new features in your application. 

Thanks for this useful application :)

**Comment by brarcher** [comment]
> Thanks for this useful application

I'm glad that the application is useful. (:  Curious, could you give some information about how you use the application and how satisfied you are with it compared to other alternatives?

I ask, as this was the first application I created for Android (so sorry it looks a bit rough). Anymore I do not put a lot of time into it. Certainly if there are changes one would be interested in providing I will accept them. Otherwise, if this application is really useful and a feature would really help out, I'll consider working on it.

**Comment by xavihernandez** [comment]
I use this application to "survey" my child.
I put a mobile phone in her bedroom as a server, and use mine as client.

I haven't tried alternatives... Yours is open source, and I use open sources applications when I can. Since yours is good (at least the baseline), I have no reason to try another one. Alternatives could be better, but yours could be enhanced thanks to community :).

No problem, it's kinda rough as you said, but working :).
I may try to do what I can to provide a pull request, but I am unsure about when I will be able to do it... :/

**Comment by brarcher** [comment]
In case you do get to it, I've converted the project to using Gradle so that it is easier to manage in Android Studio.

**Comment by xavihernandez** [comment]
Ok ok :)

**Comment by brarcher** [comment]
This should now be resolved. It will appear in the next release.

**Comment by xavihernandez** [comment]
You the man, thanks!
Btw happy new year!! Wish you all the best
